"""Program setup through the shared resource router.

These endpoints are generated by core/crud.py, so testing one resource end to end
plus the cross-tenant and role cases covers the factory for all of them.
"""

from __future__ import annotations

import uuid

import pytest
from httpx import AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import hash_password
from app.core.tenancy import tenancy_disabled
from app.models import Event, Organization, OrgMember, Role, User

PASSWORD = "correct horse battery staple"


async def _member(session: AsyncSession, org: Organization, role: Role) -> User:
    with tenancy_disabled():
        user = User(
            email=f"{role.value}-{uuid.uuid4().hex[:8]}@example.com",
            name=role.value.title(),
            password_hash=hash_password(PASSWORD),
        )
        session.add(user)
        await session.flush()
        session.add(OrgMember(org_id=org.id, user_id=user.id, role=role))
        await session.commit()
    return user


async def _event_of(session: AsyncSession, org: Organization) -> Event:
    with tenancy_disabled():
        event = await session.scalar(select(Event).where(Event.org_id == org.id))
    assert event is not None
    return event


async def _token(client: AsyncClient, user: User) -> str:
    response = await client.post("/v1/auth/login", json={"email": user.email, "password": PASSWORD})
    return str(response.json()["access_token"])


@pytest.fixture
async def coordinator(
    client: AsyncClient, session: AsyncSession, two_orgs: tuple[Organization, Organization]
) -> tuple[dict[str, str], Event]:
    org_a, _ = two_orgs
    user = await _member(session, org_a, Role.COORDINATOR)
    return {"Authorization": f"Bearer {await _token(client, user)}"}, await _event_of(
        session, org_a
    )


async def test_create_and_list_a_track(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator

    created = await client.post(
        f"/v1/events/{event.id}/tracks", json={"name": "AI Engineering"}, headers=headers
    )
    assert created.status_code == 201
    assert created.json()["name"] == "AI Engineering"

    listed = await client.get(f"/v1/events/{event.id}/tracks", headers=headers)
    assert [t["name"] for t in listed.json()] == ["AI Engineering"]


async def test_hue_is_assigned_and_stays_put(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """Track colour is stored, not derived, so it never shifts under an organizer."""
    headers, event = coordinator
    hues = []
    for name in ("AI Engineering", "Platform & Infra", "Developer Experience"):
        response = await client.post(
            f"/v1/events/{event.id}/tracks", json={"name": name}, headers=headers
        )
        hues.append(response.json()["hue_index"])

    assert hues == [1, 2, 3]

    await client.delete(f"/v1/events/{event.id}/tracks", headers=headers)  # no-op, no such route
    again = await client.get(f"/v1/events/{event.id}/tracks", headers=headers)
    assert [t["hue_index"] for t in again.json()] == [1, 2, 3]


async def test_update_and_delete_round_trip(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    created = await client.post(
        f"/v1/events/{event.id}/rooms",
        json={"name": "Main Stage", "capacity": 800},
        headers=headers,
    )
    room_id = created.json()["id"]

    patched = await client.patch(
        f"/v1/events/{event.id}/rooms/{room_id}", json={"capacity": 1200}, headers=headers
    )
    assert patched.json()["capacity"] == 1200
    assert patched.json()["name"] == "Main Stage"

    assert (
        await client.delete(f"/v1/events/{event.id}/rooms/{room_id}", headers=headers)
    ).status_code == 204
    assert (await client.get(f"/v1/events/{event.id}/rooms", headers=headers)).json() == []


async def test_unknown_id_is_a_404_not_a_500(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    response = await client.get(f"/v1/events/{event.id}/rooms/{uuid.uuid4()}", headers=headers)

    assert response.status_code == 404
    assert response.json()["error"]["code"] == "NOT_FOUND"


async def test_a_member_of_another_org_is_refused(
    client: AsyncClient, session: AsyncSession, two_orgs: tuple[Organization, Organization]
) -> None:
    """The cross-tenant case: owning org B grants nothing on org A's event."""
    org_a, org_b = two_orgs
    outsider = await _member(session, org_b, Role.OWNER)
    event_a = await _event_of(session, org_a)
    headers = {"Authorization": f"Bearer {await _token(client, outsider)}"}

    response = await client.get(f"/v1/events/{event_a.id}/tracks", headers=headers)

    assert response.status_code == 403
    assert response.json()["error"]["code"] == "ROLE_REQUIRED"


async def test_reviewers_can_read_but_not_write(
    client: AsyncClient, session: AsyncSession, two_orgs: tuple[Organization, Organization]
) -> None:
    org_a, _ = two_orgs
    reviewer = await _member(session, org_a, Role.REVIEWER)
    event = await _event_of(session, org_a)
    headers = {"Authorization": f"Bearer {await _token(client, reviewer)}"}

    assert (await client.get(f"/v1/events/{event.id}/tracks", headers=headers)).status_code == 200
    blocked = await client.post(
        f"/v1/events/{event.id}/tracks", json={"name": "Sneaky"}, headers=headers
    )
    assert blocked.status_code == 403


async def test_anonymous_access_is_refused(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    _, event = coordinator

    assert (await client.get(f"/v1/events/{event.id}/tracks")).status_code == 401


async def test_day_rejects_an_end_before_its_start(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    response = await client.post(
        f"/v1/events/{event.id}/days",
        json={"day_date": "2027-05-12", "starts_at_local": "18:00", "ends_at_local": "09:00"},
        headers=headers,
    )

    assert response.status_code == 422
    assert response.json()["error"]["code"] == "VALIDATION_FAILED"


async def test_unknown_fields_are_rejected(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    response = await client.post(
        f"/v1/events/{event.id}/tracks",
        json={"name": "Fine", "org_id": str(uuid.uuid4())},
        headers=headers,
    )

    assert response.status_code == 422
