"""Program setup through the shared resource router.

These endpoints are generated by core/crud.py, so testing one resource end to end
plus the cross-tenant and role cases covers the factory for all of them.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

import pytest
from httpx import AsyncClient
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import hash_password
from app.core.tenancy import tenancy_disabled
from app.models import Event, Organization, OrgMember, Role, User

PASSWORD = "correct horse battery staple"


async def _member(session: AsyncSession, org: Organization, role: Role) -> User:
    with tenancy_disabled():
        user = User(
            email=f"{role.value}-{uuid.uuid4().hex[:8]}@example.com",
            name=role.value.title(),
            password_hash=hash_password(PASSWORD),
            email_verified_at=datetime.now(UTC),
        )
        session.add(user)
        await session.flush()
        session.add(OrgMember(org_id=org.id, user_id=user.id, role=role))
        await session.commit()
    return user


async def _event_of(session: AsyncSession, org: Organization) -> Event:
    with tenancy_disabled():
        event = await session.scalar(select(Event).where(Event.org_id == org.id))
    assert event is not None
    return event


async def _token(client: AsyncClient, user: User) -> str:
    response = await client.post("/v1/auth/login", json={"email": user.email, "password": PASSWORD})
    return str(response.json()["access_token"])


@pytest.fixture
async def coordinator(
    client: AsyncClient, session: AsyncSession, two_orgs: tuple[Organization, Organization]
) -> tuple[dict[str, str], Event]:
    org_a, _ = two_orgs
    user = await _member(session, org_a, Role.COORDINATOR)
    return {"Authorization": f"Bearer {await _token(client, user)}"}, await _event_of(
        session, org_a
    )


async def test_create_and_list_a_track(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator

    created = await client.post(
        f"/v1/events/{event.id}/tracks", json={"name": "AI Engineering"}, headers=headers
    )
    assert created.status_code == 201
    assert created.json()["name"] == "AI Engineering"

    listed = await client.get(f"/v1/events/{event.id}/tracks", headers=headers)
    assert [t["name"] for t in listed.json()] == ["AI Engineering"]


async def test_hue_is_assigned_and_stays_put(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """Track colour is stored, not derived, so it never shifts under an organizer."""
    headers, event = coordinator
    hues = []
    for name in ("AI Engineering", "Platform & Infra", "Developer Experience"):
        response = await client.post(
            f"/v1/events/{event.id}/tracks", json={"name": name}, headers=headers
        )
        hues.append(response.json()["hue_index"])

    assert hues == [1, 2, 3]

    await client.delete(f"/v1/events/{event.id}/tracks", headers=headers)  # no-op, no such route
    again = await client.get(f"/v1/events/{event.id}/tracks", headers=headers)
    assert [t["hue_index"] for t in again.json()] == [1, 2, 3]


async def test_update_and_delete_round_trip(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    created = await client.post(
        f"/v1/events/{event.id}/rooms",
        json={"name": "Main Stage", "capacity": 800},
        headers=headers,
    )
    room_id = created.json()["id"]

    patched = await client.patch(
        f"/v1/events/{event.id}/rooms/{room_id}", json={"capacity": 1200}, headers=headers
    )
    assert patched.json()["capacity"] == 1200
    assert patched.json()["name"] == "Main Stage"

    assert (
        await client.delete(f"/v1/events/{event.id}/rooms/{room_id}", headers=headers)
    ).status_code == 204
    assert (await client.get(f"/v1/events/{event.id}/rooms", headers=headers)).json() == []


async def test_unknown_id_is_a_404_not_a_500(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    response = await client.get(f"/v1/events/{event.id}/rooms/{uuid.uuid4()}", headers=headers)

    assert response.status_code == 404
    assert response.json()["error"]["code"] == "NOT_FOUND"


async def test_a_member_of_another_org_is_refused(
    client: AsyncClient, session: AsyncSession, two_orgs: tuple[Organization, Organization]
) -> None:
    """The cross-tenant case: owning org B grants nothing on org A's event."""
    org_a, org_b = two_orgs
    outsider = await _member(session, org_b, Role.OWNER)
    event_a = await _event_of(session, org_a)
    headers = {"Authorization": f"Bearer {await _token(client, outsider)}"}

    response = await client.get(f"/v1/events/{event_a.id}/tracks", headers=headers)

    assert response.status_code == 403
    assert response.json()["error"]["code"] == "ROLE_REQUIRED"


async def test_reviewers_can_read_but_not_write(
    client: AsyncClient, session: AsyncSession, two_orgs: tuple[Organization, Organization]
) -> None:
    org_a, _ = two_orgs
    reviewer = await _member(session, org_a, Role.REVIEWER)
    event = await _event_of(session, org_a)
    headers = {"Authorization": f"Bearer {await _token(client, reviewer)}"}

    assert (await client.get(f"/v1/events/{event.id}/tracks", headers=headers)).status_code == 200
    blocked = await client.post(
        f"/v1/events/{event.id}/tracks", json={"name": "Sneaky"}, headers=headers
    )
    assert blocked.status_code == 403


async def test_anonymous_access_is_refused(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    _, event = coordinator

    assert (await client.get(f"/v1/events/{event.id}/tracks")).status_code == 401


async def test_day_rejects_an_end_before_its_start(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    response = await client.post(
        f"/v1/events/{event.id}/days",
        json={"day_date": "2027-05-12", "starts_at_local": "18:00", "ends_at_local": "09:00"},
        headers=headers,
    )

    assert response.status_code == 422
    assert response.json()["error"]["code"] == "VALIDATION_FAILED"


# The conference runs 2027-05-10 → 2027-05-22 (the `two_orgs` fixture). A day is
# a date the conference runs on, so the window is the whole rule: a date outside
# it draws an agenda tab for a day nobody is there, and a date in the past is
# only the loudest instance of that.
@pytest.mark.parametrize(
    ("day", "why"),
    [
        ("2027-05-09", "the day before it opens"),
        ("2027-05-23", "the day after it closes"),
        ("2019-01-01", "years in the past"),
        ("2099-01-01", "far in the future"),
    ],
)
async def test_a_day_outside_the_event_window_is_refused(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event], day: str, why: str
) -> None:
    headers, event = coordinator
    response = await client.post(
        f"/v1/events/{event.id}/days",
        json={"day_date": day, "starts_at_local": "09:00", "ends_at_local": "18:00"},
        headers=headers,
    )

    assert response.status_code == 422, f"{day} ({why}) was accepted"
    body = response.json()["error"]
    assert body["code"] == "VALIDATION_FAILED"
    # The message has to name the window, or the organiser is told "no" and left
    # guessing which dates are allowed.
    assert "2027-05-10" in body["message"] and "2027-05-22" in body["message"]


@pytest.mark.parametrize("day", ["2027-05-10", "2027-05-16", "2027-05-22"])
async def test_the_first_and_last_day_of_the_event_are_valid(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event], day: str
) -> None:
    """The window is inclusive at both ends — a one-day conference has one legal
    date, and an off-by-one here makes the opening day unaddable."""
    headers, event = coordinator
    response = await client.post(
        f"/v1/events/{event.id}/days",
        json={"day_date": day, "starts_at_local": "09:00", "ends_at_local": "18:00"},
        headers=headers,
    )

    assert response.status_code == 201, response.text


async def test_a_day_cannot_be_edited_out_of_the_event_window(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """The create check is worth nothing on its own: the edit drawer is the same
    date field, and moving a day drags every session placed on it along."""
    headers, event = coordinator
    day_id = (
        await client.post(
            f"/v1/events/{event.id}/days",
            json={"day_date": "2027-05-12", "starts_at_local": "09:00", "ends_at_local": "18:00"},
            headers=headers,
        )
    ).json()["id"]

    response = await client.patch(
        f"/v1/events/{event.id}/days/{day_id}",
        json={"day_date": "2026-01-01"},
        headers=headers,
    )

    assert response.status_code == 422
    assert response.json()["error"]["code"] == "VALIDATION_FAILED"


async def test_unknown_fields_are_rejected(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    response = await client.post(
        f"/v1/events/{event.id}/tracks",
        json={"name": "Fine", "org_id": str(uuid.uuid4())},
        headers=headers,
    )

    assert response.status_code == 422


async def _placed_session(
    client: AsyncClient, headers: dict[str, str], event: Event, *, day: str = "2027-05-12"
) -> tuple[str, str, str]:
    """A session on a day, in a room, at a time — the shape every cascade acts on."""
    room_id = (
        await client.post(f"/v1/events/{event.id}/rooms", json={"name": "Hall"}, headers=headers)
    ).json()["id"]
    day_id = (
        await client.post(
            f"/v1/events/{event.id}/days",
            json={"day_date": day, "starts_at_local": "09:00", "ends_at_local": "18:00"},
            headers=headers,
        )
    ).json()["id"]
    session_id = (
        await client.post(
            f"/v1/events/{event.id}/sessions", json={"title": "Keynote"}, headers=headers
        )
    ).json()["id"]
    placed = await client.patch(
        f"/v1/events/{event.id}/sessions/{session_id}/placement",
        json={
            "event_day_id": day_id,
            "room_id": room_id,
            "starts_at": f"{day}T09:00:00Z",
        },
        headers=headers,
    )
    assert placed.status_code == 200, placed.text
    return day_id, room_id, session_id


async def test_deleting_a_day_with_sessions_on_it_is_refused(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """Days had no guard at all.

    `sessions.event_day_id` is SET NULL while the time, the room and the
    scheduled status stay, so the session became undrawable: not on any day's
    tab, and not in the tray either.
    """
    headers, event = coordinator
    day_id, _room_id, session_id = await _placed_session(client, headers, event)

    refused = await client.delete(f"/v1/events/{event.id}/days/{day_id}", headers=headers)

    assert refused.status_code == 409
    assert refused.json()["error"]["code"] == "CONFLICT"
    assert "1 session" in refused.json()["error"]["message"]

    still_there = await client.get(f"/v1/events/{event.id}/sessions", headers=headers)
    placed = next(row for row in still_there.json() if row["id"] == session_id)
    assert placed["event_day_id"] == day_id


async def test_deleting_a_room_in_use_names_what_is_in_it(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    _day_id, room_id, _session_id = await _placed_session(client, headers, event)

    refused = await client.delete(f"/v1/events/{event.id}/rooms/{room_id}", headers=headers)

    assert refused.status_code == 409
    # The old message said "still use this" for every resource; a room holding a
    # session and a room holding a break are different problems to fix.
    assert "in this room" in refused.json()["error"]["message"]


async def test_a_day_that_moves_takes_its_sessions_with_it(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """`starts_at` is absolute UTC and does not follow the day row.

    Editing the date without shifting them left every talk sitting on the old
    date, still marked scheduled, invisible on the tab it belonged to.
    """
    headers, event = coordinator
    day_id, _room_id, session_id = await _placed_session(client, headers, event)

    moved = await client.patch(
        f"/v1/events/{event.id}/days/{day_id}", json={"day_date": "2027-05-14"}, headers=headers
    )
    assert moved.status_code == 200

    listing = await client.get(f"/v1/events/{event.id}/sessions", headers=headers)
    row = next(entry for entry in listing.json() if entry["id"] == session_id)
    assert row["starts_at"].startswith("2027-05-14T09:00")


async def test_editing_a_day_without_moving_it_leaves_sessions_alone(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    headers, event = coordinator
    day_id, _room_id, session_id = await _placed_session(client, headers, event)

    renamed = await client.patch(
        f"/v1/events/{event.id}/days/{day_id}", json={"label": "Workshop day"}, headers=headers
    )
    assert renamed.status_code == 200

    listing = await client.get(f"/v1/events/{event.id}/sessions", headers=headers)
    row = next(entry for entry in listing.json() if entry["id"] == session_id)
    assert row["starts_at"].startswith("2027-05-12T09:00")


async def test_an_unused_day_still_deletes(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """The guard refuses what is in use and nothing else."""
    headers, event = coordinator
    day_id = (
        await client.post(
            f"/v1/events/{event.id}/days",
            json={"day_date": "2027-05-13", "starts_at_local": "09:00", "ends_at_local": "18:00"},
            headers=headers,
        )
    ).json()["id"]

    assert (
        await client.delete(f"/v1/events/{event.id}/days/{day_id}", headers=headers)
    ).status_code == 204


async def test_every_row_carries_what_it_would_cost_to_remove(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """The count is the warning. The 409 is enforcement, and it arrives too late
    to be one — a screen has to be able to say "2 sessions" beside the button."""
    headers, event = coordinator
    day_id, room_id, _session_id = await _placed_session(client, headers, event)

    days = (await client.get(f"/v1/events/{event.id}/days", headers=headers)).json()
    rooms = (await client.get(f"/v1/events/{event.id}/rooms", headers=headers)).json()

    assert next(row for row in days if row["id"] == day_id)["session_count"] == 1
    assert next(row for row in rooms if row["id"] == room_id)["session_count"] == 1

    spare = await client.post(
        f"/v1/events/{event.id}/rooms", json={"name": "Empty room"}, headers=headers
    )
    assert spare.json()["session_count"] == 0

    # The edit reports what it touched: moving a day returns the count of what
    # moved with it, so a screen can confirm rather than predict.
    moved = await client.patch(
        f"/v1/events/{event.id}/days/{day_id}", json={"day_date": "2027-05-15"}, headers=headers
    )
    assert moved.json()["session_count"] == 1


async def test_a_day_cannot_be_edited_to_end_before_it_starts(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """A one-sided edit: only the start moves, and it lands after the stored end."""
    headers, event = coordinator
    day_id = (
        await client.post(
            f"/v1/events/{event.id}/days",
            json={"day_date": "2027-05-12", "starts_at_local": "09:00", "ends_at_local": "18:00"},
            headers=headers,
        )
    ).json()["id"]

    refused = await client.patch(
        f"/v1/events/{event.id}/days/{day_id}", json={"starts_at_local": "19:00"}, headers=headers
    )

    assert refused.status_code == 422
    assert refused.json()["error"]["code"] == "VALIDATION_FAILED"

    unchanged = (await client.get(f"/v1/events/{event.id}/days/{day_id}", headers=headers)).json()
    assert unchanged["starts_at_local"] == "09:00:00"


async def test_adding_a_day_that_already_exists_is_refused_not_a_500(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """`unique(event_id, day_date)` was doing its job and nobody caught it.

    Adding a date already in the list raised an IntegrityError straight through
    to a bare 500, which tells an organiser nothing about what they did.
    """
    headers, event = coordinator
    day = {"day_date": "2027-05-12", "starts_at_local": "09:00", "ends_at_local": "18:00"}
    assert (
        await client.post(f"/v1/events/{event.id}/days", json=day, headers=headers)
    ).status_code == 201

    again = await client.post(f"/v1/events/{event.id}/days", json=day, headers=headers)

    assert again.status_code == 409
    assert again.json()["error"]["code"] == "CONFLICT"
    assert "already an event day" in again.json()["error"]["message"]


async def test_two_rooms_cannot_share_a_name(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """`unique(event_id, name)` is in the brief for rooms, tracks and formats.

    Without it the agenda drew two columns called Main Stage and a placement
    could land in either.
    """
    headers, event = coordinator
    assert (
        await client.post(
            f"/v1/events/{event.id}/rooms", json={"name": "Main Stage"}, headers=headers
        )
    ).status_code == 201

    clash = await client.post(
        f"/v1/events/{event.id}/rooms", json={"name": "Main Stage"}, headers=headers
    )

    assert clash.status_code == 409
    assert "already has a room" in clash.json()["error"]["message"]


async def test_renaming_a_track_onto_another_name_is_refused(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """The edit path has the same constraint and used to 500 the same way."""
    headers, event = coordinator
    await client.post(f"/v1/events/{event.id}/tracks", json={"name": "AI"}, headers=headers)
    other = await client.post(
        f"/v1/events/{event.id}/tracks", json={"name": "Platform"}, headers=headers
    )

    clash = await client.patch(
        f"/v1/events/{event.id}/tracks/{other.json()['id']}",
        json={"name": "AI"},
        headers=headers,
    )

    assert clash.status_code == 409
    assert "already has a track" in clash.json()["error"]["message"]


async def test_a_day_row_says_what_it_actually_holds(
    client: AsyncClient, coordinator: tuple[dict[str, str], Event]
) -> None:
    """A date and an opening window cannot answer "is this day built yet?".

    The hours occupied are the ones sessions are in, not the ones the day is
    open — an empty day reporting 09:00-18:00 would look scheduled.
    """
    headers, event = coordinator
    day_id, _room_id, _session_id = await _placed_session(client, headers, event)

    days = (await client.get(f"/v1/events/{event.id}/days", headers=headers)).json()
    built = next(row for row in days if row["id"] == day_id)

    assert built["session_count"] == 1
    assert built["room_count"] == 1
    assert built["first_session_at"].startswith("2027-05-12T09:00")
    assert built["last_session_at"].startswith("2027-05-12T09:00")

    empty_id = (
        await client.post(
            f"/v1/events/{event.id}/days", json={"day_date": "2027-05-20"}, headers=headers
        )
    ).json()["id"]
    empty = next(
        row
        for row in (await client.get(f"/v1/events/{event.id}/days", headers=headers)).json()
        if row["id"] == empty_id
    )
    assert empty["session_count"] == 0
    assert empty["first_session_at"] is None
