"use client";

/** Mounts the landing prototype's own behaviour onto the converted markup.
 *
 * `DesignMotion` already drives what every converted screen shares — the
 * [data-rv] reveals, [data-rule] wipes and [data-count] count-ups. This adds
 * what only the landing has: seven looping product demos, the annotation
 * arrows, and the parallax layers.
 *
 * Rendered as a sibling of `<GatherLanding />` rather than inside it, because
 * that component is generated by `tools/dc2tsx.py` and overwritten on every
 * design change.
 *
 * Both this and marketing.css hang off one `data-marketing` attribute on the
 * element wrapping the landing. The v6 prototype labels its sections but leaves
 * its own root bare, so there is nothing in the generated markup stable enough
 * to select on — and a scope that a redesign can silently remove would take the
 * page's whole stylesheet with it.
 */

import { useEffect } from "react";

import { agendaDrag } from "./agenda-demo";
import {
  arrows,
  commandPalette,
  embedSnippet,
  formBuilder,
  parallax,
  portalTask,
  reviewQueue,
  sendDecisions,
  settlePalette,
  type Demo,
} from "./demos";

const DEMOS: readonly Demo[] = [
  arrows,
  parallax,
  formBuilder,
  reviewQueue,
  sendDecisions,
  portalTask,
  embedSnippet,
  commandPalette,
  agendaDrag,
];

export function LandingMotion({ annotations = true }: { annotations?: boolean }) {
  useEffect(() => {
    const root = document.querySelector<HTMLElement>("[data-marketing]");
    if (root === null) return;

    if (!annotations) {
      for (const note of root.querySelectorAll<HTMLElement>(
        "[data-ann],[data-arrow],[data-heroann]",
      )) {
        note.style.display = "none";
      }
    }

    // Nothing here is load-bearing: every demo is decoration over markup that
    // already reads correctly, so honouring the preference costs no meaning.
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      settlePalette(root);
      return;
    }

    const teardowns = DEMOS.map((demo) => demo(root));
    return () => teardowns.forEach((teardown) => teardown());
  }, [annotations]);

  return null;
}
