"""full schema

Revision ID: 76514830ef57
Revises: 772fa3dead63
Create Date: 2026-08-09 00:44:37.492954
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "76514830ef57"
down_revision: str | None = "772fa3dead63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speakers",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("pronouns", sa.String(length=60), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("job_title", sa.String(length=200), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("headshot_file_id", sa.UUID(), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("dietary_notes", sa.Text(), nullable=True),
        sa.Column("accessibility_notes", sa.Text(), nullable=True),
        sa.Column("av_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_speakers_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speakers")),
        sa.UniqueConstraint("org_id", "email", name=op.f("uq_speakers_org_id_email")),
    )
    op.create_index(op.f("ix_speakers_org_id"), "speakers", ["org_id"], unique=False)
    op.create_table(
        "activity_log",
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_speaker_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_kind",
            sa.Enum("user", "speaker", "system", "ai", name="actor_kind"),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_speaker_id"],
            ["speakers.id"],
            name=op.f("fk_activity_log_actor_speaker_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_activity_log_actor_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_activity_log_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_activity_log_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_log")),
    )
    op.create_index(
        "ix_activity_log_entity",
        "activity_log",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_activity_log_event_created", "activity_log", ["event_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_activity_log_org_id"), "activity_log", ["org_id"], unique=False)
    op.create_table(
        "ai_proposals",
        sa.Column(
            "kind",
            sa.Enum(
                "schedule",
                "duplicates",
                "normalize",
                "score",
                "assign_reviewers",
                name="ai_proposal_kind",
            ),
            nullable=False,
        ),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "streaming",
                "ready",
                "partially_accepted",
                "accepted",
                "discarded",
                "failed",
                name="ai_proposal_status",
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_ai_proposals_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_ai_proposals_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_ai_proposals_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_proposals")),
    )
    op.create_index(op.f("ix_ai_proposals_event_id"), "ai_proposals", ["event_id"], unique=False)
    op.create_index(op.f("ix_ai_proposals_org_id"), "ai_proposals", ["org_id"], unique=False)
    op.create_table(
        "conflict_dismissals",
        sa.Column("conflict_key", sa.String(length=120), nullable=False),
        sa.Column(
            "kind", sa.Enum("room", "speaker", "track", name="conflict_kind"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("dismissed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dismissed_by_user_id"],
            ["users.id"],
            name=op.f("fk_conflict_dismissals_dismissed_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_conflict_dismissals_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_conflict_dismissals_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conflict_dismissals")),
        sa.UniqueConstraint(
            "event_id", "conflict_key", name=op.f("uq_conflict_dismissals_event_id_conflict_key")
        ),
    )
    op.create_index(
        op.f("ix_conflict_dismissals_event_id"), "conflict_dismissals", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_conflict_dismissals_org_id"), "conflict_dismissals", ["org_id"], unique=False
    )
    op.create_table(
        "event_days",
        sa.Column("day_date", sa.Date(), nullable=False),
        sa.Column("starts_at_local", sa.Time(), nullable=False),
        sa.Column("ends_at_local", sa.Time(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_days_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_event_days_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_days")),
        sa.UniqueConstraint("event_id", "day_date", name=op.f("uq_event_days_event_id_day_date")),
    )
    op.create_index(op.f("ix_event_days_event_id"), "event_days", ["event_id"], unique=False)
    op.create_index(op.f("ix_event_days_org_id"), "event_days", ["org_id"], unique=False)
    op.create_table(
        "event_speakers",
        sa.Column("speaker_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "prospective",
                "accepted",
                "confirmed",
                "declined",
                "withdrawn",
                name="speaker_status",
            ),
            nullable=False,
        ),
        sa.Column("portal_last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_speakers_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_event_speakers_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
            name=op.f("fk_event_speakers_speaker_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_speakers")),
        sa.UniqueConstraint(
            "event_id", "speaker_id", name=op.f("uq_event_speakers_event_id_speaker_id")
        ),
    )
    op.create_index(
        op.f("ix_event_speakers_event_id"), "event_speakers", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_event_speakers_org_id"), "event_speakers", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_event_speakers_speaker_id"), "event_speakers", ["speaker_id"], unique=False
    )
    op.create_index(op.f("ix_event_speakers_status"), "event_speakers", ["status"], unique=False)
    op.create_table(
        "files",
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("version_group_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(length=600), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=160), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by_speaker_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_files_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_files_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_speaker_id"],
            ["speakers.id"],
            name=op.f("fk_files_uploaded_by_speaker_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_files_uploaded_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint(
            "version_group_id", "version", name=op.f("uq_files_version_group_id_version")
        ),
    )
    op.create_index(op.f("ix_files_event_id"), "files", ["event_id"], unique=False)
    op.create_index(op.f("ix_files_org_id"), "files", ["org_id"], unique=False)
    op.create_index(
        "ix_files_version_group_version", "files", ["version_group_id", "version"], unique=False
    )
    op.create_table(
        "forms",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.Enum("cfp", "task", name="form_kind"), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Enum("draft", "open", "closed", name="form_status"), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_forms_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_forms_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forms")),
    )
    op.create_index(op.f("ix_forms_event_id"), "forms", ["event_id"], unique=False)
    op.create_index(op.f("ix_forms_org_id"), "forms", ["org_id"], unique=False)
    op.create_table(
        "integration_configs",
        sa.Column("provider", sa.Enum("accelevents", name="integration_provider"), nullable=False),
        sa.Column("credentials_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("remote_event_id", sa.String(length=200), nullable=True),
        sa.Column("field_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_integration_configs_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_integration_configs_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_configs")),
        sa.UniqueConstraint(
            "event_id", "provider", name=op.f("uq_integration_configs_event_id_provider")
        ),
    )
    op.create_index(
        op.f("ix_integration_configs_event_id"), "integration_configs", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_integration_configs_org_id"), "integration_configs", ["org_id"], unique=False
    )
    op.create_table(
        "message_templates",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "acceptance",
                "rejection",
                "waitlist",
                "task_reminder",
                "schedule_change",
                "portal_invite",
                "reviewer_nudge",
                "custom",
                name="message_purpose",
            ),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("attach_ics", sa.Boolean(), nullable=False),
        sa.Column("include_calendar_links", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_message_templates_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_message_templates_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_templates")),
    )
    op.create_index(
        op.f("ix_message_templates_event_id"), "message_templates", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_templates_org_id"), "message_templates", ["org_id"], unique=False
    )
    op.create_table(
        "pages",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("draft", "speakers_only", "public", name="page_visibility"),
            nullable=False,
        ),
        sa.Column("is_pinned_in_portal", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_pages_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_pages_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("event_id", "slug", name=op.f("uq_pages_event_id_slug")),
    )
    op.create_index(op.f("ix_pages_event_id"), "pages", ["event_id"], unique=False)
    op.create_index(op.f("ix_pages_org_id"), "pages", ["org_id"], unique=False)
    op.create_table(
        "published_schedules",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_by_user_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_published_schedules_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_published_schedules_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_published_schedules_published_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_published_schedules")),
        sa.UniqueConstraint(
            "event_id", "version", name=op.f("uq_published_schedules_event_id_version")
        ),
    )
    op.create_index(
        op.f("ix_published_schedules_event_id"), "published_schedules", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_published_schedules_org_id"), "published_schedules", ["org_id"], unique=False
    )
    op.create_table(
        "review_rounds",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_blind", sa.Boolean(), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("advance_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "open", "closed", name="review_round_status"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_review_rounds_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_review_rounds_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_rounds")),
    )
    op.create_index(op.f("ix_review_rounds_event_id"), "review_rounds", ["event_id"], unique=False)
    op.create_index(op.f("ix_review_rounds_org_id"), "review_rounds", ["org_id"], unique=False)
    op.create_table(
        "rooms",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("av_notes", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_rooms_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_rooms_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
    )
    op.create_index(op.f("ix_rooms_event_id"), "rooms", ["event_id"], unique=False)
    op.create_index(op.f("ix_rooms_org_id"), "rooms", ["org_id"], unique=False)
    op.create_table(
        "saved_views",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("table_key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_saved_views_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_saved_views_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_views_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_views")),
    )
    op.create_index(op.f("ix_saved_views_event_id"), "saved_views", ["event_id"], unique=False)
    op.create_index(op.f("ix_saved_views_org_id"), "saved_views", ["org_id"], unique=False)
    op.create_index(op.f("ix_saved_views_user_id"), "saved_views", ["user_id"], unique=False)
    op.create_table(
        "session_formats",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("default_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("icon_key", sa.String(length=60), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_session_formats_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_session_formats_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_formats")),
    )
    op.create_index(
        op.f("ix_session_formats_event_id"), "session_formats", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_session_formats_org_id"), "session_formats", ["org_id"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hue_index", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_tracks_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_tracks_org_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracks")),
    )
    op.create_index(op.f("ix_tracks_event_id"), "tracks", ["event_id"], unique=False)
    op.create_index(op.f("ix_tracks_org_id"), "tracks", ["org_id"], unique=False)
    op.create_table(
        "form_field_stats",
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("submission_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_form_field_stats_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["form_id"], ["forms.id"], name=op.f("fk_form_field_stats_form_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_form_field_stats_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form_field_stats")),
        sa.UniqueConstraint("form_id", name=op.f("uq_form_field_stats_form_id")),
    )
    op.create_index(
        op.f("ix_form_field_stats_event_id"), "form_field_stats", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_form_field_stats_org_id"), "form_field_stats", ["org_id"], unique=False
    )
    op.create_table(
        "integration_pushes",
        sa.Column("integration_config_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("dry_run", "execute", name="push_kind"), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_integration_pushes_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_integration_pushes_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["integration_config_id"],
            ["integration_configs.id"],
            name=op.f("fk_integration_pushes_integration_config_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_integration_pushes_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_pushes")),
    )
    op.create_index(
        op.f("ix_integration_pushes_event_id"), "integration_pushes", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_integration_pushes_integration_config_id"),
        "integration_pushes",
        ["integration_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_pushes_org_id"), "integration_pushes", ["org_id"], unique=False
    )
    op.create_table(
        "message_batches",
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("recipient_count", sa.Integer(), nullable=False),
        sa.Column("segment_description", sa.String(length=400), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "queued", "sent", "failed", "bounced", "complained", name="message_status"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_message_batches_created_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_message_batches_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_message_batches_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["message_templates.id"],
            name=op.f("fk_message_batches_template_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_batches")),
    )
    op.create_index(
        op.f("ix_message_batches_event_id"), "message_batches", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_message_batches_org_id"), "message_batches", ["org_id"], unique=False)
    op.create_table(
        "room_blackouts",
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_room_blackouts_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_room_blackouts_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_room_blackouts_room_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_blackouts")),
    )
    op.create_index(
        op.f("ix_room_blackouts_event_id"), "room_blackouts", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_room_blackouts_org_id"), "room_blackouts", ["org_id"], unique=False)
    op.create_index(op.f("ix_room_blackouts_room_id"), "room_blackouts", ["room_id"], unique=False)
    op.create_table(
        "rubric_criteria",
        sa.Column("review_round_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scale_min", sa.Integer(), nullable=False),
        sa.Column("scale_max", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_rubric_criteria_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_rubric_criteria_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_round_id"],
            ["review_rounds.id"],
            name=op.f("fk_rubric_criteria_review_round_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rubric_criteria")),
    )
    op.create_index(
        op.f("ix_rubric_criteria_event_id"), "rubric_criteria", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_rubric_criteria_org_id"), "rubric_criteria", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_rubric_criteria_review_round_id"),
        "rubric_criteria",
        ["review_round_id"],
        unique=False,
    )
    op.create_table(
        "schedule_blocks",
        sa.Column("event_day_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("spans_all_rooms", sa.Boolean(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_day_id"],
            ["event_days.id"],
            name=op.f("fk_schedule_blocks_event_day_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_schedule_blocks_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_schedule_blocks_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_schedule_blocks_room_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_blocks")),
    )
    op.create_index(
        op.f("ix_schedule_blocks_event_day_id"), "schedule_blocks", ["event_day_id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_blocks_event_id"), "schedule_blocks", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_schedule_blocks_org_id"), "schedule_blocks", ["org_id"], unique=False)
    op.create_table(
        "submissions",
        sa.Column("form_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=True),
        sa.Column("session_format_id", sa.UUID(), nullable=True),
        sa.Column("requested_duration_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "in_review",
                "accepted",
                "waitlisted",
                "rejected",
                "withdrawn",
                name="submission_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "decision_status",
            sa.Enum("none", "pending_send", "sent", name="decision_status"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_user_id", sa.UUID(), nullable=True),
        sa.Column("coordinator_user_id", sa.UUID(), nullable=True),
        sa.Column("score_avg", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("draft_token", sa.UUID(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coordinator_user_id"],
            ["users.id"],
            name=op.f("fk_submissions_coordinator_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_submissions_decided_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_submissions_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["form_id"], ["forms.id"], name=op.f("fk_submissions_form_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_submissions_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_format_id"],
            ["session_formats.id"],
            name=op.f("fk_submissions_session_format_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_submissions_track_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
        sa.UniqueConstraint("draft_token", name=op.f("uq_submissions_draft_token")),
        sa.UniqueConstraint("event_id", "code", name=op.f("uq_submissions_event_id_code")),
    )
    op.create_index(op.f("ix_submissions_event_id"), "submissions", ["event_id"], unique=False)
    op.create_index(
        "ix_submissions_event_id_decision_status",
        "submissions",
        ["event_id", "decision_status"],
        unique=False,
    )
    op.create_index(
        "ix_submissions_event_id_score_avg", "submissions", ["event_id", "score_avg"], unique=False
    )
    op.create_index(
        "ix_submissions_event_id_status", "submissions", ["event_id", "status"], unique=False
    )
    op.create_index(op.f("ix_submissions_org_id"), "submissions", ["org_id"], unique=False)
    op.create_table(
        "task_templates",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("upload", "form", "acknowledge", "external_link", name="task_kind"),
            nullable=False,
        ),
        sa.Column("form_id", sa.UUID(), nullable=True),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("due_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applies_to", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("accepted_file_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_file_mb", sa.Integer(), nullable=True),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_task_templates_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["form_id"], ["forms.id"], name=op.f("fk_task_templates_form_id"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_task_templates_org_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_templates")),
    )
    op.create_index(
        op.f("ix_task_templates_event_id"), "task_templates", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_task_templates_org_id"), "task_templates", ["org_id"], unique=False)
    op.create_table(
        "ai_scores",
        sa.Column("review_round_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("rubric_criterion_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_ai_scores_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_ai_scores_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["review_round_id"],
            ["review_rounds.id"],
            name=op.f("fk_ai_scores_review_round_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rubric_criterion_id"],
            ["rubric_criteria.id"],
            name=op.f("fk_ai_scores_rubric_criterion_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_ai_scores_submission_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_scores")),
        sa.UniqueConstraint(
            "review_round_id",
            "submission_id",
            "rubric_criterion_id",
            name=op.f("uq_ai_scores_review_round_id_submission_id_rubric_criterion_id"),
        ),
    )
    op.create_index(op.f("ix_ai_scores_event_id"), "ai_scores", ["event_id"], unique=False)
    op.create_index(op.f("ix_ai_scores_org_id"), "ai_scores", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_ai_scores_submission_id"), "ai_scores", ["submission_id"], unique=False
    )
    op.create_table(
        "duplicate_flags",
        sa.Column("submission_a_id", sa.UUID(), nullable=False),
        sa.Column("submission_b_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("overlap_spans", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "kept_both", "marked_duplicate", "merged", name="duplicate_status"),
            nullable=False,
        ),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_duplicate_flags_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_duplicate_flags_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_duplicate_flags_resolved_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submission_a_id"],
            ["submissions.id"],
            name=op.f("fk_duplicate_flags_submission_a_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_b_id"],
            ["submissions.id"],
            name=op.f("fk_duplicate_flags_submission_b_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicate_flags")),
        sa.UniqueConstraint(
            "submission_a_id",
            "submission_b_id",
            name=op.f("uq_duplicate_flags_submission_a_id_submission_b_id"),
        ),
    )
    op.create_index(
        op.f("ix_duplicate_flags_event_id"), "duplicate_flags", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_duplicate_flags_org_id"), "duplicate_flags", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_duplicate_flags_submission_a_id"),
        "duplicate_flags",
        ["submission_a_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("message_template_id", sa.UUID(), nullable=True),
        sa.Column("batch_id", sa.UUID(), nullable=True),
        sa.Column("to_email", postgresql.CITEXT(), nullable=False),
        sa.Column("to_speaker_id", sa.UUID(), nullable=True),
        sa.Column("to_user_id", sa.UUID(), nullable=True),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body_rendered", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "queued", "sent", "failed", "bounced", "complained", name="message_status"
            ),
            nullable=False,
        ),
        sa.Column("ses_message_id", sa.String(length=200), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bounced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ics_attached", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["message_batches.id"],
            name=op.f("fk_messages_batch_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_messages_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["message_template_id"],
            ["message_templates.id"],
            name=op.f("fk_messages_message_template_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_messages_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_speaker_id"],
            ["speakers.id"],
            name=op.f("fk_messages_to_speaker_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"], ["users.id"], name=op.f("fk_messages_to_user_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_batch_id"), "messages", ["batch_id"], unique=False)
    op.create_index(op.f("ix_messages_event_id"), "messages", ["event_id"], unique=False)
    op.create_index(
        "ix_messages_event_status_sent", "messages", ["event_id", "status", "sent_at"], unique=False
    )
    op.create_index(op.f("ix_messages_org_id"), "messages", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_messages_ses_message_id"), "messages", ["ses_message_id"], unique=False
    )
    op.create_index("ix_messages_to_speaker_id", "messages", ["to_speaker_id"], unique=False)
    op.create_table(
        "reviewer_assignments",
        sa.Column("review_round_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_reviewer_assignments_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_reviewer_assignments_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_round_id"],
            ["review_rounds.id"],
            name=op.f("fk_reviewer_assignments_review_round_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_reviewer_assignments_submission_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reviewer_assignments_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviewer_assignments")),
        sa.UniqueConstraint(
            "review_round_id",
            "submission_id",
            "user_id",
            name=op.f("uq_reviewer_assignments_review_round_id_submission_id_user_id"),
        ),
    )
    op.create_index(
        op.f("ix_reviewer_assignments_event_id"), "reviewer_assignments", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviewer_assignments_org_id"), "reviewer_assignments", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviewer_assignments_submission_id"),
        "reviewer_assignments",
        ["submission_id"],
        unique=False,
    )
    op.create_index(
        "ix_reviewer_assignments_user_round_completed",
        "reviewer_assignments",
        ["user_id", "review_round_id", "completed_at"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("review_round_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "scored", "skipped", "flagged", name="review_status"),
            nullable=False,
        ),
        sa.Column("conflict_of_interest", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_reviews_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_reviews_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["review_round_id"],
            ["review_rounds.id"],
            name=op.f("fk_reviews_review_round_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_reviews_submission_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reviews_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint(
            "review_round_id",
            "submission_id",
            "user_id",
            name=op.f("uq_reviews_review_round_id_submission_id_user_id"),
        ),
    )
    op.create_index(op.f("ix_reviews_event_id"), "reviews", ["event_id"], unique=False)
    op.create_index(op.f("ix_reviews_org_id"), "reviews", ["org_id"], unique=False)
    op.create_index(
        "ix_reviews_round_user_status",
        "reviews",
        ["review_round_id", "user_id", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_reviews_submission_id"), "reviews", ["submission_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("submission_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=True),
        sa.Column("session_format_id", sa.UUID(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("event_day_id", sa.UUID(), nullable=True),
        sa.Column("room_id", sa.UUID(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("unscheduled", "scheduled", "confirmed", name="session_status"),
            nullable=False,
        ),
        sa.Column("materials_url", sa.String(length=500), nullable=True),
        sa.Column("recording_embed_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_day_id"],
            ["event_days.id"],
            name=op.f("fk_sessions_event_day_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_sessions_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_sessions_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_sessions_room_id"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_format_id"],
            ["session_formats.id"],
            name=op.f("fk_sessions_session_format_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_sessions_submission_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["tracks.id"], name=op.f("fk_sessions_track_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("event_id", "slug", name=op.f("uq_sessions_event_id_slug")),
    )
    op.create_index(op.f("ix_sessions_event_id"), "sessions", ["event_id"], unique=False)
    op.create_index("ix_sessions_event_id_status", "sessions", ["event_id", "status"], unique=False)
    op.create_index(op.f("ix_sessions_org_id"), "sessions", ["org_id"], unique=False)
    op.create_index(
        "ix_sessions_placement",
        "sessions",
        ["event_id", "event_day_id", "room_id", "starts_at"],
        unique=False,
    )
    op.create_table(
        "speaker_tasks",
        sa.Column("speaker_id", sa.UUID(), nullable=False),
        sa.Column("task_template_id", sa.UUID(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "not_started", "in_progress", "submitted", "complete", "overdue", name="task_status"
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("form_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_nudged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
            name=op.f("fk_speaker_tasks_completed_by_user_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_speaker_tasks_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_speaker_tasks_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
            name=op.f("fk_speaker_tasks_speaker_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_template_id"],
            ["task_templates.id"],
            name=op.f("fk_speaker_tasks_task_template_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speaker_tasks")),
        sa.UniqueConstraint(
            "speaker_id",
            "task_template_id",
            name=op.f("uq_speaker_tasks_speaker_id_task_template_id"),
        ),
    )
    op.create_index(op.f("ix_speaker_tasks_event_id"), "speaker_tasks", ["event_id"], unique=False)
    op.create_index(
        "ix_speaker_tasks_event_status_due",
        "speaker_tasks",
        ["event_id", "status", "due_at"],
        unique=False,
    )
    op.create_index(op.f("ix_speaker_tasks_org_id"), "speaker_tasks", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_speaker_tasks_speaker_id"), "speaker_tasks", ["speaker_id"], unique=False
    )
    op.create_table(
        "submission_notes",
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_submission_notes_author_user_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_submission_notes_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_submission_notes_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_notes_submission_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_notes")),
    )
    op.create_index(
        op.f("ix_submission_notes_event_id"), "submission_notes", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_notes_org_id"), "submission_notes", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_notes_submission_id"),
        "submission_notes",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "submission_speakers",
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("speaker_id", sa.UUID(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_submission_speakers_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_submission_speakers_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
            name=op.f("fk_submission_speakers_speaker_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_speakers_submission_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_speakers")),
        sa.UniqueConstraint(
            "submission_id",
            "speaker_id",
            name=op.f("uq_submission_speakers_submission_id_speaker_id"),
        ),
    )
    op.create_index(
        op.f("ix_submission_speakers_event_id"), "submission_speakers", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_speakers_org_id"), "submission_speakers", ["org_id"], unique=False
    )
    op.create_index(
        "ix_submission_speakers_speaker_id", "submission_speakers", ["speaker_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_speakers_submission_id"),
        "submission_speakers",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "submission_tags",
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_submission_tags_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_submission_tags_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_tags_submission_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_tags")),
        sa.UniqueConstraint(
            "submission_id", "label", name=op.f("uq_submission_tags_submission_id_label")
        ),
    )
    op.create_index(
        op.f("ix_submission_tags_event_id"), "submission_tags", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_submission_tags_org_id"), "submission_tags", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_submission_tags_submission_id"), "submission_tags", ["submission_id"], unique=False
    )
    op.create_table(
        "review_scores",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("rubric_criterion_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_review_scores_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_review_scores_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name=op.f("fk_review_scores_review_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rubric_criterion_id"],
            ["rubric_criteria.id"],
            name=op.f("fk_review_scores_rubric_criterion_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_scores")),
        sa.UniqueConstraint(
            "review_id",
            "rubric_criterion_id",
            name=op.f("uq_review_scores_review_id_rubric_criterion_id"),
        ),
    )
    op.create_index(op.f("ix_review_scores_event_id"), "review_scores", ["event_id"], unique=False)
    op.create_index(op.f("ix_review_scores_org_id"), "review_scores", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_review_scores_review_id"), "review_scores", ["review_id"], unique=False
    )
    op.create_table(
        "session_speakers",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("speaker_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("speaker", "moderator", "panelist", name="session_speaker_role"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_session_speakers_event_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_session_speakers_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_speakers_session_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.id"],
            name=op.f("fk_session_speakers_speaker_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_speakers")),
        sa.UniqueConstraint(
            "session_id", "speaker_id", name=op.f("uq_session_speakers_session_id_speaker_id")
        ),
    )
    op.create_index(
        op.f("ix_session_speakers_event_id"), "session_speakers", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_speakers_org_id"), "session_speakers", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_speakers_session_id"), "session_speakers", ["session_id"], unique=False
    )
    op.create_index(
        "ix_session_speakers_speaker_id", "session_speakers", ["speaker_id"], unique=False
    )
    op.create_table(
        "task_files",
        sa.Column("speaker_task_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_task_files_event_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_task_files_file_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.id"], name=op.f("fk_task_files_org_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["speaker_task_id"],
            ["speaker_tasks.id"],
            name=op.f("fk_task_files_speaker_task_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_files")),
        sa.UniqueConstraint(
            "speaker_task_id", "file_id", name=op.f("uq_task_files_speaker_task_id_file_id")
        ),
    )
    op.create_index(op.f("ix_task_files_event_id"), "task_files", ["event_id"], unique=False)
    op.create_index(op.f("ix_task_files_org_id"), "task_files", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_task_files_speaker_task_id"), "task_files", ["speaker_task_id"], unique=False
    )

    op.execute(
        """
        ALTER TABLE submissions
        ADD COLUMN search_vector tsvector
        GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(answers::text, '')), 'B')
        ) STORED
        """
    )
    op.execute("CREATE INDEX ix_submissions_search_vector ON submissions USING GIN (search_vector)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_files_speaker_task_id"), table_name="task_files")
    op.drop_index(op.f("ix_task_files_org_id"), table_name="task_files")
    op.drop_index(op.f("ix_task_files_event_id"), table_name="task_files")
    op.drop_table("task_files")
    op.drop_index("ix_session_speakers_speaker_id", table_name="session_speakers")
    op.drop_index(op.f("ix_session_speakers_session_id"), table_name="session_speakers")
    op.drop_index(op.f("ix_session_speakers_org_id"), table_name="session_speakers")
    op.drop_index(op.f("ix_session_speakers_event_id"), table_name="session_speakers")
    op.drop_table("session_speakers")
    op.drop_index(op.f("ix_review_scores_review_id"), table_name="review_scores")
    op.drop_index(op.f("ix_review_scores_org_id"), table_name="review_scores")
    op.drop_index(op.f("ix_review_scores_event_id"), table_name="review_scores")
    op.drop_table("review_scores")
    op.drop_index(op.f("ix_submission_tags_submission_id"), table_name="submission_tags")
    op.drop_index(op.f("ix_submission_tags_org_id"), table_name="submission_tags")
    op.drop_index(op.f("ix_submission_tags_event_id"), table_name="submission_tags")
    op.drop_table("submission_tags")
    op.drop_index(op.f("ix_submission_speakers_submission_id"), table_name="submission_speakers")
    op.drop_index("ix_submission_speakers_speaker_id", table_name="submission_speakers")
    op.drop_index(op.f("ix_submission_speakers_org_id"), table_name="submission_speakers")
    op.drop_index(op.f("ix_submission_speakers_event_id"), table_name="submission_speakers")
    op.drop_table("submission_speakers")
    op.drop_index(op.f("ix_submission_notes_submission_id"), table_name="submission_notes")
    op.drop_index(op.f("ix_submission_notes_org_id"), table_name="submission_notes")
    op.drop_index(op.f("ix_submission_notes_event_id"), table_name="submission_notes")
    op.drop_table("submission_notes")
    op.drop_index(op.f("ix_speaker_tasks_speaker_id"), table_name="speaker_tasks")
    op.drop_index(op.f("ix_speaker_tasks_org_id"), table_name="speaker_tasks")
    op.drop_index("ix_speaker_tasks_event_status_due", table_name="speaker_tasks")
    op.drop_index(op.f("ix_speaker_tasks_event_id"), table_name="speaker_tasks")
    op.drop_table("speaker_tasks")
    op.drop_index("ix_sessions_placement", table_name="sessions")
    op.drop_index(op.f("ix_sessions_org_id"), table_name="sessions")
    op.drop_index("ix_sessions_event_id_status", table_name="sessions")
    op.drop_index(op.f("ix_sessions_event_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_reviews_submission_id"), table_name="reviews")
    op.drop_index("ix_reviews_round_user_status", table_name="reviews")
    op.drop_index(op.f("ix_reviews_org_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_event_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_reviewer_assignments_user_round_completed", table_name="reviewer_assignments")
    op.drop_index(op.f("ix_reviewer_assignments_submission_id"), table_name="reviewer_assignments")
    op.drop_index(op.f("ix_reviewer_assignments_org_id"), table_name="reviewer_assignments")
    op.drop_index(op.f("ix_reviewer_assignments_event_id"), table_name="reviewer_assignments")
    op.drop_table("reviewer_assignments")
    op.drop_index("ix_messages_to_speaker_id", table_name="messages")
    op.drop_index(op.f("ix_messages_ses_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_org_id"), table_name="messages")
    op.drop_index("ix_messages_event_status_sent", table_name="messages")
    op.drop_index(op.f("ix_messages_event_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_batch_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_duplicate_flags_submission_a_id"), table_name="duplicate_flags")
    op.drop_index(op.f("ix_duplicate_flags_org_id"), table_name="duplicate_flags")
    op.drop_index(op.f("ix_duplicate_flags_event_id"), table_name="duplicate_flags")
    op.drop_table("duplicate_flags")
    op.drop_index(op.f("ix_ai_scores_submission_id"), table_name="ai_scores")
    op.drop_index(op.f("ix_ai_scores_org_id"), table_name="ai_scores")
    op.drop_index(op.f("ix_ai_scores_event_id"), table_name="ai_scores")
    op.drop_table("ai_scores")
    op.drop_index(op.f("ix_task_templates_org_id"), table_name="task_templates")
    op.drop_index(op.f("ix_task_templates_event_id"), table_name="task_templates")
    op.drop_table("task_templates")
    op.drop_index(op.f("ix_submissions_org_id"), table_name="submissions")
    op.drop_index("ix_submissions_event_id_status", table_name="submissions")
    op.drop_index("ix_submissions_event_id_score_avg", table_name="submissions")
    op.drop_index("ix_submissions_event_id_decision_status", table_name="submissions")
    op.drop_index(op.f("ix_submissions_event_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_schedule_blocks_org_id"), table_name="schedule_blocks")
    op.drop_index(op.f("ix_schedule_blocks_event_id"), table_name="schedule_blocks")
    op.drop_index(op.f("ix_schedule_blocks_event_day_id"), table_name="schedule_blocks")
    op.drop_table("schedule_blocks")
    op.drop_index(op.f("ix_rubric_criteria_review_round_id"), table_name="rubric_criteria")
    op.drop_index(op.f("ix_rubric_criteria_org_id"), table_name="rubric_criteria")
    op.drop_index(op.f("ix_rubric_criteria_event_id"), table_name="rubric_criteria")
    op.drop_table("rubric_criteria")
    op.drop_index(op.f("ix_room_blackouts_room_id"), table_name="room_blackouts")
    op.drop_index(op.f("ix_room_blackouts_org_id"), table_name="room_blackouts")
    op.drop_index(op.f("ix_room_blackouts_event_id"), table_name="room_blackouts")
    op.drop_table("room_blackouts")
    op.drop_index(op.f("ix_message_batches_org_id"), table_name="message_batches")
    op.drop_index(op.f("ix_message_batches_event_id"), table_name="message_batches")
    op.drop_table("message_batches")
    op.drop_index(op.f("ix_integration_pushes_org_id"), table_name="integration_pushes")
    op.drop_index(
        op.f("ix_integration_pushes_integration_config_id"), table_name="integration_pushes"
    )
    op.drop_index(op.f("ix_integration_pushes_event_id"), table_name="integration_pushes")
    op.drop_table("integration_pushes")
    op.drop_index(op.f("ix_form_field_stats_org_id"), table_name="form_field_stats")
    op.drop_index(op.f("ix_form_field_stats_event_id"), table_name="form_field_stats")
    op.drop_table("form_field_stats")
    op.drop_index(op.f("ix_tracks_org_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_event_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_session_formats_org_id"), table_name="session_formats")
    op.drop_index(op.f("ix_session_formats_event_id"), table_name="session_formats")
    op.drop_table("session_formats")
    op.drop_index(op.f("ix_saved_views_user_id"), table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_org_id"), table_name="saved_views")
    op.drop_index(op.f("ix_saved_views_event_id"), table_name="saved_views")
    op.drop_table("saved_views")
    op.drop_index(op.f("ix_rooms_org_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_event_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_review_rounds_org_id"), table_name="review_rounds")
    op.drop_index(op.f("ix_review_rounds_event_id"), table_name="review_rounds")
    op.drop_table("review_rounds")
    op.drop_index(op.f("ix_published_schedules_org_id"), table_name="published_schedules")
    op.drop_index(op.f("ix_published_schedules_event_id"), table_name="published_schedules")
    op.drop_table("published_schedules")
    op.drop_index(op.f("ix_pages_org_id"), table_name="pages")
    op.drop_index(op.f("ix_pages_event_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_message_templates_org_id"), table_name="message_templates")
    op.drop_index(op.f("ix_message_templates_event_id"), table_name="message_templates")
    op.drop_table("message_templates")
    op.drop_index(op.f("ix_integration_configs_org_id"), table_name="integration_configs")
    op.drop_index(op.f("ix_integration_configs_event_id"), table_name="integration_configs")
    op.drop_table("integration_configs")
    op.drop_index(op.f("ix_forms_org_id"), table_name="forms")
    op.drop_index(op.f("ix_forms_event_id"), table_name="forms")
    op.drop_table("forms")
    op.drop_index("ix_files_version_group_version", table_name="files")
    op.drop_index(op.f("ix_files_org_id"), table_name="files")
    op.drop_index(op.f("ix_files_event_id"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_event_speakers_status"), table_name="event_speakers")
    op.drop_index(op.f("ix_event_speakers_speaker_id"), table_name="event_speakers")
    op.drop_index(op.f("ix_event_speakers_org_id"), table_name="event_speakers")
    op.drop_index(op.f("ix_event_speakers_event_id"), table_name="event_speakers")
    op.drop_table("event_speakers")
    op.drop_index(op.f("ix_event_days_org_id"), table_name="event_days")
    op.drop_index(op.f("ix_event_days_event_id"), table_name="event_days")
    op.drop_table("event_days")
    op.drop_index(op.f("ix_conflict_dismissals_org_id"), table_name="conflict_dismissals")
    op.drop_index(op.f("ix_conflict_dismissals_event_id"), table_name="conflict_dismissals")
    op.drop_table("conflict_dismissals")
    op.drop_index(op.f("ix_ai_proposals_org_id"), table_name="ai_proposals")
    op.drop_index(op.f("ix_ai_proposals_event_id"), table_name="ai_proposals")
    op.drop_table("ai_proposals")
    op.drop_index(op.f("ix_activity_log_org_id"), table_name="activity_log")
    op.drop_index("ix_activity_log_event_created", table_name="activity_log")
    op.drop_index("ix_activity_log_entity", table_name="activity_log")
    op.drop_table("activity_log")
    op.drop_index(op.f("ix_speakers_org_id"), table_name="speakers")
    op.drop_table("speakers")
    # ### end Alembic commands ###

    # Autogenerate never drops the enum types it created; orphans make the
    # next upgrade fail with DuplicateObjectError.
    op.execute("DROP TYPE IF EXISTS actor_kind")
    op.execute("DROP TYPE IF EXISTS ai_proposal_kind")
    op.execute("DROP TYPE IF EXISTS ai_proposal_status")
    op.execute("DROP TYPE IF EXISTS conflict_kind")
    op.execute("DROP TYPE IF EXISTS decision_status")
    op.execute("DROP TYPE IF EXISTS duplicate_status")
    op.execute("DROP TYPE IF EXISTS form_kind")
    op.execute("DROP TYPE IF EXISTS form_status")
    op.execute("DROP TYPE IF EXISTS integration_provider")
    op.execute("DROP TYPE IF EXISTS message_purpose")
    op.execute("DROP TYPE IF EXISTS message_status")
    op.execute("DROP TYPE IF EXISTS page_visibility")
    op.execute("DROP TYPE IF EXISTS push_kind")
    op.execute("DROP TYPE IF EXISTS review_round_status")
    op.execute("DROP TYPE IF EXISTS review_status")
    op.execute("DROP TYPE IF EXISTS session_speaker_role")
    op.execute("DROP TYPE IF EXISTS session_status")
    op.execute("DROP TYPE IF EXISTS speaker_status")
    op.execute("DROP TYPE IF EXISTS submission_status")
    op.execute("DROP TYPE IF EXISTS task_kind")
    op.execute("DROP TYPE IF EXISTS task_status")
