"""session content approval

Revision ID: a63f0094d8ea
Revises: a89b2d688b72
Create Date: 2026-08-09 13:06:46.771322
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a63f0094d8ea"
down_revision: str | None = "a89b2d688b72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    sa.Enum("pending", "approved", "changes_requested", name="content_status").create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills rows that predate the column; it is then dropped so
    # the model and the schema agree and autogenerate reports no drift.
    op.add_column(
        "sessions",
        sa.Column(
            "content_status",
            sa.Enum("pending", "approved", "changes_requested", name="content_status"),
            nullable=False,
            server_default="pending",
        ),
    )
    op.alter_column("sessions", "content_status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "content_status")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS content_status")
