"""scorecard criterion kinds

Revision ID: a89b2d688b72
Revises: d273550b0db8
Create Date: 2026-08-09 10:44:51.719587
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a89b2d688b72"
down_revision: str | None = "d273550b0db8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate emits the column but not the CREATE TYPE when an enum is added
    # to a table that already exists.
    sa.Enum("rating", "select", "text", name="criterion_kind").create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review_scores", sa.Column("value_text", sa.Text(), nullable=True))
    op.alter_column("review_scores", "value", existing_type=sa.INTEGER(), nullable=True)
    op.add_column(
        "rubric_criteria",
        sa.Column(
            "kind", sa.Enum("rating", "select", "text", name="criterion_kind"), nullable=False
        ),
    )
    op.add_column(
        "rubric_criteria",
        sa.Column("choices", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rubric_criteria", "choices")
    op.drop_column("rubric_criteria", "kind")
    op.alter_column("review_scores", "value", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("review_scores", "value_text")
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS criterion_kind")
