"""speaker password

Revision ID: d273550b0db8
Revises: 76514830ef57
Create Date: 2026-08-09 09:26:35.383805
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d273550b0db8"
down_revision: str | None = "76514830ef57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("speakers", sa.Column("password_hash", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("speakers", "password_hash")
    # ### end Alembic commands ###
